fuzzing_engines:
- libfuzzer
homepage: https://github.com/vitessio/vitess
language: go
main_repo: https://github.com/vitessio/vitess
sanitizers:
- address
vendor_ccs:
- adam@adalogics.com
- david@adalogics.com
