homepage: https://dawn.googlesource.com
language: c++
primary_contact: bclayton@google.com
auto_ccs:
  - "alanbaker@google.com"
  - "amaiorano@google.com"
  - "dneto@google.com"
  - "dsinclair@chromium.org"
  - "jrprice@google.com"
  - "rharrison@chromium.org"
sanitizers:
  - address
  - memory
  - undefined
main_repo: 'https://dawn.googlesource.com/dawn.git'
architectures:
  - x86_64
  - i386
