homepage: "https://fluxcd.io/"
main_repo: "https://github.com/fluxcd/flux2"
primary_contact: "michael@weave.works"
auto_ccs :
  - "stefan@weave.works"
  - "hidde@weave.works"
  - "david@adalogics.com"
  - "adam@adalogics.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
