homepage: "https://www.bouncycastle.org/"
language: jvm
primary_contact: "metzman@chromium.org"
main_repo: "https://github.com/bcgit/bc-java.git"
fuzzing_engines:
  - "wycheproof"
sanitizers:
  - "none"
file_github_issue: false
disabled: true
