homepage: "http://facebook.github.io/zstd/"
language: c++
primary_contact: "terrelln@fb.com"
auto_ccs:
  - "NickRTerrell@gmail.com"
  - "Yann.collet.73@gmail.com"
  - "cyan@fb.com"
  - "felixh@fb.com"
  - "dpc@fb.com"
  - "hmf@fb.com"
  - "yaohway@fb.com"
  - "axxu@fb.com"
  - "binhvo@fb.com"
  - "embg@fb.com"
  - "yoniko@fb.com"
  - "sangelov@fb.com"
vendor_ccs:
  - "oss-fuzz@fb.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - memory
  - undefined
main_repo: 'https://github.com/facebook/zstd'
