homepage: "https://github.com/HdrHistogram/HdrHistogram.git"
language: jvm
primary_contact: "wagner@code-intelligence.com"
auto_ccs:
  - "wagner@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "glendowne@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
fuzzing_engines:
  - libfuzzer
main_repo: "https://github.com/HdrHistogram/HdrHistogram.git"
sanitizers:
  - address
