fuzzing_engines:
- libfuzzer
homepage: https://github.com/grpc/grpc
language: python
main_repo: https://github.com/grpc/grpc
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
- adam@adalogics.com
