homepage: "https://commons.apache.org/proper/commons-configuration/"
language: jvm
main_repo: "https://gitbox.apache.org/repos/asf/commons-configuration.git"
fuzzing_engines:
 - libfuzzer
sanitizers:
 - address
vendor_ccs:
 - "wagner@code-intelligence.com"
 - "yakdan@code-intelligence.com"
 - "glendowne@code-intelligence.com"
 - "patrice.salathe@code-intelligence.com"
 - "hlin@code-intelligence.com"
 - "yoshi.weber@gmail.com"
