homepage: "https://opendal.apache.org/"
main_repo: "https://github.com/apache/incubator-opendal.git"
language: rust
primary_contact: "xuanwo.cn@gmail.com"
auto_ccs:
    - "dqhl76@gmail.com"
vendor_ccs:
    - "commits@opendal.apache.org"
sanitizers:
  - address
fuzzing_engines:
  - libfuzzer
file_github_issue: True