homepage: "https://github.com/mkleehammer/pyodbc"
language: python
main_repo: "https://github.com/mkleehammer/pyodbc"
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
- adam@adalogics.com
