homepage: "https://github.com/microsoft/msquic"
language: c
primary_contact: "msquicinfra@microsoft.com"
auto_ccs:
  - "quicdev@microsoft.com"
  - "daikiaminaka@microsoft.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
main_repo: 'https://github.com/microsoft/msquic.git'
