version: 2
updates:
- package-ecosystem: pip
  directory: "/infra/ci"
  schedule:
    interval: daily
- package-ecosystem: pip
  directory: "/infra/build/functions"
  schedule:
    interval: daily
- package-ecosystem: pip
  directory: "/infra/cifuzz"
  schedule:
    interval: daily
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
