allowedCopyrightHolders:
  - 'Google LLC'
allowedLicenses:
  - 'Apache-2.0'
sourceFileExtensions:
  - 'ts'
  - 'js'
  - 'java'
  - 'Dockerfile'
  - 'js'
  - 'java'
  - 'c'
  - 'h'
  - 'cc'
  - 'cpp'
  - 'css'
  - 'html'
  - 'htm'
  - 'go'
  - 'sh'
  - 'bash'
  - 'rs'
  - 'proto'
