homepage: "http://www.javassist.org/"
language: jvm
primary_contact: "wagner@code-intelligence.com"
auto_ccs:
  - "wagner@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "glendowne@code-intelligence.com"
fuzzing_engines:
  - libfuzzer
main_repo: "https://github.com/jboss-javassist/javassist"
sanitizers:
  - address
