homepage: "https://cloud.spring.io/spring-cloud-netflix/reference/html/"
language: jvm
main_repo: "https://github.com/spring-cloud/spring-cloud-netflix.git"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
primary_contact: "pwebb@vmware.com"
vendor_ccs:
  - "wilkinsona@vmware.com"
  - "wagner@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "glendowne@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
  - "hlin@code-intelligence.com"
  - "schaich@code-intelligence.com"