homepage: "https://www.spice-space.org/usbredir.html"
language: c++
primary_contact: "freddy77@gmail.com"
auto_ccs:
  - "imsnah@gmail.com"
sanitizers:
  - address
  - memory
  - undefined
main_repo: "https://gitlab.freedesktop.org/spice/usbredir.git"
