homepage: "https://github.com/GoogleCloudPlatform/config-validator/"
main_repo: "https://github.com/GoogleCloudPlatform/config-validator/"
primary_contact: "martin.p.petkov@gmail.com"
auto_ccs:
- morgantep@google.com
language: go
fuzzing_engines:
- libfuzzer
sanitizers:
- address
