homepage: "https://surrealdb.com/"
language: rust
primary_contact: "tobie@surrealdb.com"
main_repo: "https://github.com/surrealdb/surrealdb"
auto_ccs:
  - finn.bear@surrealdb.com
  - nathaniel.brough@gmail.com

sanitizers:
  - address
fuzzing_engines:
  - libfuzzer