homepage: "https://github.com/FasterXML/jackson-core"
language: jvm
primary_contact: "tatu@fasterxml.com"
auto_ccs:
  - "meumertzheim@code-intelligence.com"
  - "norbert.schneider@code-intelligence.com"
  - "hlin@code-intelligence.com"
  - "Adam@adalogics.com"
  - "David@adalogics.com"
  - "fanningpj@gmail.com"
fuzzing_engines:
  - libfuzzer
main_repo: "https://github.com/FasterXML/jackson-core"
sanitizers:
  - address
