homepage: "https://github.com/spring-cloud/spring-cloud-commons"
language: jvm
main_repo: "https://github.com/spring-cloud/spring-cloud-commons.git"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
vendor_ccs:
  - "wagner@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "glendowne@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com" 