homepage: "https://github.com/websocket-client/websocket-client"
language: python
main_repo: "https://github.com/websocket-client/websocket-client"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
vendor_ccs:
  - david@adalogics.com
