homepage: "https://clickhouse.com/"
language: c++
primary_contact: "security@clickhouse.com"
auto_ccs:
 - "jakalletti@gmail.com"
 - "man2gm@gmail.com"
 - "kochetovnicolai@gmail.com"
 - "hq.zero.iq@gmail.com"
 - "milovidov@clickhouse.com"
sanitizers:
 - address
 - memory
 - undefined
fuzzing_engines:
 - libfuzzer
main_repo: 'https://github.com/ClickHouse/ClickHouse.git'
