homepage: "https://github.com/spdk/spdk"
main_repo: "https://github.com/spdk/spdk"
language: c
primary_contact: "james.r.harris@intel.com"
auto_ccs:
  - "Adam@adalogics.com"
  - "tomasz.zawadzki@intel.com"
  - "konrad.sztyber@intel.com"
  - "MichalX.Berger@intel.com"
sanitizers:
  - address
  - undefined
  - memory
