homepage: "https://commons.apache.org/proper/commons-io/"
language: jvm
primary_contact: "glendowne@code-intelligence.com"
auto_ccs:
  - "wagner@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
  - "yakdan@code-intelligence.com"
fuzzing_engines:
  - "libfuzzer"
sanitizers:
  - "address"
main_repo: "https://gitbox.apache.org/repos/asf/commons-io.git"
