homepage: "https://www.djangoproject.com/"
language: python
primary_contact: "f.apolloner@gmail.com"
auto_ccs:
  - "jammamarkus@gmail.com"
  - "guidovranken@gmail.com"
  - "info+django+security@markusholtermann.eu"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
main_repo: "https://github.com/django/django.git"
