homepage: "https://freedesktop.org/wiki/Software/pyxdg/"
main_repo: "https://github.com/takluyver/pyxdg"
language: python
primary_contact: "david@adalogics.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
