homepage: "https://bitbucket.org/snakeyaml/snakeyaml/src/master/"
language: jvm
primary_contact: "glendowne@code-intelligence.com"
auto_ccs:
  - "wagner@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
  - "yakdan@code-intelligence.com"
fuzzing_engines:
  - "libfuzzer"
sanitizers:
  - "address"
main_repo: "https://bitbucket.org/snakeyaml/snakeyaml.git"
