homepage: "https://github.com/pallets/flask"
main_repo: "https://github.com/pallets/flask"
language: python
primary_contact: "david@adalogics.com"
auto_ccs:
  - "adam@adalogics.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
