homepage: "https://www.ruby-lang.org/"
language: c
primary_contact: "yukihiro@gmail.com"
auto_ccs:
  - "hsbt@ruby-lang.org"
  - "kateinoigakukun@gmail.com"
  - "zn@mbf.nifty.com"
  - "mame@ruby-lang.org"
  - "john@hawthorn.email"
  - "kevinbackhouse@github.com"
main_repo: "https://github.com/ruby/ruby"
