homepage: "https://www.ruby-lang.org/"
language: c
primary_contact: "yukihiro@gmail.com"
auto_ccs:
  - "nobu.nakada@gmail.com"
  - "shibata.hiroshi@gmail.com"
  - "kateinoigakukun@gmail.com"
  - "zn@mbf.nifty.com"
  - "y.endoh@gmail.com"
  - "john@hawthorn.email"
  - "kevinbackhouse@github.com"
  - "oss-fuzz@ruby-lang.org"
fuzzing_engines:
  - libfuzzer
  - honggfuzz
  - afl
  # - centipede disabled due to https://github.com/google/oss-fuzz/pull/10248#issuecomment-1579657163
main_repo: "https://github.com/ruby/ruby"
