homepage: "https://github.com/pandas-dev/pandas"
language: python
main_repo: "https://github.com/pandas-dev/pandas"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
vendor_ccs:
  - david@adalogics.com
  - adam@adalogics.com
