homepage: "https://github.com/googleapis/google-auth-library-python-oauthlib"
language: python
main_repo: "https://github.com/googleapis/google-auth-library-python-oauthlib"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
vendor_ccs:
  - david@adalogics.com
