homepage: "https://github.com/starkbank/ecdsa-python"
language: python
primary_contact: "david@adalogics.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: "https://github.com/starkbank/ecdsa-python/"
