homepage: "https://github.com/qos-ch/logback"
language: jvm
primary_contact: "dev.qos.ch@gmail.com"
auto_ccs:
  - "wagner@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "glendowne@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
  - "hlin@code-intelligence.com"  
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: "https://github.com/qos-ch/logback.git"