fuzzing_engines:
- libfuzzer
homepage: https://github.com/kvesteri/sqlalchemy-utils
language: python
primary_contact: "contactme@kurtmckee.org"
main_repo: https://github.com/kvesteri/sqlalchemy-utils
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
- adam@adalogics.com
- arthur.chan@adalogics.com
