homepage: "https://github.com/go-gitea/gitea"
primary_contact: "security@gitea.io"
auto_ccs :
  - "adam@adalogics.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: "https://github.com/go-gitea/gitea"
