homepage: "https://github.com/scikit-learn/scikit-learn"
language: python
main_repo: "https://github.com/scikit-learn/scikit-learn"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
vendor_ccs:
  - david@adalogics.com
