homepage: "https://github.com/rossmacarthur/serde"
language: python
main_repo: "https://github.com/rossmacarthur/serde"
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
- adam@adalogics.com
- arthur.chan@adalogics.com
