homepage: "https://u-root.org/"
main_repo: "https://github.com/u-root/u-root.git"
primary_contact: "rminnich@gmail.com"
auto_ccs:
  - "fab.wienand@gmail.com"
language: go
architectures:
  - x86_64
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
