homepage: "https://www.python.org/"
main_repo: "https://github.com/python/cpython"
language: c
primary_contact: "guidovranken@gmail.com"
auto_ccs:
 - "gps@google.com"
 - "alex.gaynor@gmail.com"
 - "ammar@ammaraskar.com"
 - "pablogsal@python.org"
fuzzing_engines:
  - libfuzzer
  - honggfuzz
sanitizers:
 - address
 - undefined
