homepage: "https://github.com/martinblech/xmltodict"
language: python
fuzzing_engines:
      - libfuzzer
sanitizers:
      - address
      - undefined
main_repo: "https://github.com/martinblech/xmltodict.git"
primary_contact: cneo@google.com
auto_ccs:
- "david@adalogics.com"
