homepage: "https://github.com/kjd/idna"
language: python
primary_contact: "kim@cynosure.com.au"
main_repo: "https://github.com/kjd/idna"
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
- adam@adalogics.com
