fuzzing_engines:
- libfuzzer
homepage: https://github.com/googleapis/python-storage
language: python
main_repo: https://github.com/googleapis/python-storage
sanitizers:
- address
- undefined
primary_contact: "gorcester@google.com"
vendor_ccs:
- david@adalogics.com
- adam@adalogics.com
- arthur.chan@adalogics.com
