homepage: "http://nginx.org"
main_repo: "https://github.com/nginx/nginx"
language: c
primary_contact: "xim.andrew@gmail.com"
auto_ccs:
  - ouyangyunshu@google.com
  - mmoroz@google.com
  - david@adalogics.com
sanitizers:
  - address
