homepage: "https://github.com/anchore/grype/blob/main/README.md"
main_repo: "https://github.com/anchore/grype"
primary_contact: "christopher.phillips@anchore.com"
auto_ccs:
  - alex.goodman@anchore.com
  - keith.zantow@anchore.com
  - nurmi@anchore.com
  - josh.bressers@anchore.com
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
