homepage: "https://freeradius.org"
language: c++
primary_contact: "a.cudbardb@freeradius.org"
auto_ccs:
- "p.antoine@catenacyber.fr"
main_repo: 'https://github.com/FreeRADIUS/freeradius-server.git'
fuzzing_engines:
- libfuzzer
sanitizers:
- address
