fuzzing_engines:
- libfuzzer
homepage: https://github.com/tobgu/pyrsistent
language: python
main_repo: https://github.com/tobgu/pyrsistent
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
- riccardo.schirone@trailofbits.com
- facundo.tuesca@trailofbits.com
