homepage: "https://commons.apache.org"
language: jvm
primary_contact: "boards@gmail.com"
auto_ccs:
  - "fuzz-testing@commons.apache.org"
  - "brunodepaulak@gmail.com"
  - "meumertzheim@code-intelligence.com"
  - "peteralfredlee@gmail.com"
  - "norbert.schneider@code-intelligence.com"
  - "wagner@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "glendowne@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
  - "hlin@code-intelligence.com"
  - "schaich@code-intelligence.com"
fuzzing_engines:
  - libfuzzer
main_repo: "https://gitbox.apache.org/repos/asf/commons-compress.git"
sanitizers:
  - address
