homepage: "https://thesofproject.github.io"
primary_contact: "andyross@google.com"
language: c
auto_ccs:
  - "cujomalainey@chromium.org"
  - "ranjani.sridharan@intel.corp-partner.google.com"
  - "lgirdwood@gmail.com"
  - "sathyanarayana.nujella@intel.corp-partner.google.com"
  - "adrian.bonislawski@intel.com"
  - "michal.wasko@intel.com"
  - "jyri.sarha@intel.com"
  - "rander.wang@intel.com"
  - "flavio.ceolin@intel.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
architectures:
  - i386
main_repo: "https://github.com/thesofproject/sof"
