homepage: "https://github.com/CESNET/libyang"
main_repo: 'https://github.com/CESNET/libyang'
primary_contact: "mvasko@cesnet.cz"
language: c
auto_ccs :
  - "david@adalogics.com"
sanitizers:
  - address
  - memory
