fuzzing_engines:
- libfuzzer
homepage: https://github.com/astanin/python-tabulate
language: python
main_repo: https://github.com/astanin/python-tabulate
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
- adam@adalogics.com
- riccardo.schirone@trailofbits.com
- facundo.tuesca@trailofbits.com
