homepage: "https://github.com/astanin/python-tabulate"
language: python
main_repo: "https://github.com/astanin/python-tabulate"
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
- adam@adalogics.com
