homepage: "https://github.com/looker-open-source/sdk-codegen"
language: python
main_repo: "https://github.com/looker-open-source/sdk-codegen"
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
- adam@adalogics.com
