homepage: https://github.com/jsonpickle/jsonpickle
main_repo: https://github.com/jsonpickle/jsonpickle
language: python
fuzzing_engines:
- libfuzzer
sanitizers:
- address
vendor_ccs:
- david@adalogics.com
