auto_ccs:
- protobuf-oss-fuzz@google.com
- jgm@google.com
- jgrimes@google.com
- pzd@google.com
- acozzette@google.com
- deannagarcia@google.com
- gberg@google.com
- haberman@google.com
- jieluo@google.com
- jorg@google.com
- mcyoung@google.com
- mkruskal@google.com
- salo@google.com
- sandyzhang@google.com
- sbenza@google.com
- shaod@google.com
- theodorerose@google.com
- meumertzheim@code-intelligence.com
- norbert.schneider@code-intelligence.com
- hlin@code-intelligence.com
fuzzing_engines:
- libfuzzer
homepage: https://developers.google.com/protocol-buffers/
language: jvm
main_repo: https://github.com/protocolbuffers/protobuf
primary_contact: kfm@google.com
sanitizers:
- address
