homepage: "https://avro.apache.org/"
language: jvm
fuzzing_engines:
  - libfuzzer
main_repo: "https://github.com/apache/avro"
sanitizers:
  - address
primary_contact: "mgrigorov@apache.org"
vendor_ccs:
  - "wagner@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
  - "hlin@code-intelligence.com"
  - "bug-disclosure@code-intelligence.com"