fuzzing_engines:
- libfuzzer
homepage: https://github.com/apache/commons-jxpath.git
language: jvm
main_repo: https://github.com/apache/commons-jxpath.git
sanitizers:
- address
vendor_ccs:
- wagner@code-intelligence.com
- yakdan@code-intelligence.com
- glendowne@code-intelligence.com
- patrice.salathe@code-intelligence.com
- hlin@code-intelligence.com