homepage: "https://github.com/antlr/stringtemplate4"
language: jvm
primary_contact: "parrt@antlr.org"
auto_ccs:
  - "glendowne@code-intelligence.com"
  - "wagner@code-intelligence.com"
  - "yakdan@code-intelligence.com"
fuzzing_engines:
  - "libfuzzer"
sanitizers:
  - "address"
main_repo: "https://github.com/antlr/stringtemplate4.git"
