homepage: https://sharp.pixelplumbing.com/
language: javascript
main_repo: https://github.com/lovell/sharp
fuzzing_engines:
- libfuzzer
sanitizers:
- none
primary_contact: "lovell.fuller@gmail.com"
vendor_ccs:
  - "wagner@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "glendowne@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
  - "hlin@code-intelligence.com"
  - "christopher.krah@code-intelligence.com"
  - "bug-disclosure@code-intelligence.com"
