homepage: "https://github.com/uber/h3"
language: c
primary_contact: "isaac@isaacbrodsky.com"
auto_ccs:
  - "Adam@adalogics.com"
  - "h3-dev@googlegroups.com"
sanitizers:
  - address
  - undefined
  - memory
main_repo: 'https://github.com/uber/h3'
