homepage: "https://github.com/uber/h3"
language: c
primary_contact: "isaacbrodsky@live.com"
auto_ccs:
  - "Adam@adalogics.com"
  - "h3-dev@googlegroups.com"
  - "isv.damocles@gmail.com"
sanitizers:
  - address
  - undefined
  - memory
main_repo: 'https://github.com/uber/h3'
