homepage: "https://github.com/CodeIntelligenceTesting/jazzer"
disabled: false
language: jvm
primary_contact: "meumertzheim@code-intelligence.com"
fuzzing_engines:
  - libfuzzer
main_repo: "https://github.com/CodeIntelligenceTesting/jazzer"
sanitizers:
  - address
  - undefined
