homepage: "https://github.com/biydnd/et_xmlfile"
language: python
main_repo: "https://github.com/biydnd/et_xmlfile"
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
- adam@adalogics.com
