homepage: "https://github.com/google/jwt_verify_lib"
language: c++
primary_contact: "qiwzhang@google.com"
auto_ccs:
- "nareddyt@google.com"
- "yangshuo@google.com"
- "taoxuy@google.com"
main_repo: 'https://github.com/google/jwt_verify_lib.git'
