homepage: "https://github.com/google/go-containerregistry"
language: go
primary_contact: "jason@chainguard.dev"
main_repo: "https://github.com/google/go-containerregistry"
vendor_ccs:
  - "adam@adalogics.com"
  - "david@adalogics.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
