homepage: "https://github.com/tendermint/tendermint"
primary_contact: "security@tendermint.com"
auto_ccs:
  - fuzzing@orijtech.com
  - emmanuel@orijtech.com
  - cuong@orijtech.com
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: "https://github.com/tendermint/tendermint"
