homepage: "https://github.com/tendermint/tendermint"
primary_contact: "security@interchain.io"
auto_ccs:
  - fuzzing@orijtech.com
  - emmanuel@orijtech.com
  - cuong@orijtech.com
  - tess@interchain.io
  - tychoish@interchain.io
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: "https://github.com/tendermint/tendermint"
