homepage: "https://www.webtoolkit.eu/wt"
language: c++
primary_contact: "wt-security@emweb.be"
auto_ccs:
  - "ajsinghyadav00@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
main_repo: 'https://github.com/emweb/wt'
