homepage: "https://github.com/gravitational/teleport"
language: go
primary_contact: "reed@goteleport.com"
main_repo: "https://github.com/gravitational/teleport"
auto_ccs:
  - "oss-fuzz@goteleport.com"
  - "zac.bergquist@goteleport.com"
  - "jakub.nyckowski@goteleport.com"
  - "ossfuzz1337@gmail.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
