homepage: "https://github.com/gravitational/teleport"
main_repo: "https://github.com/gravitational/teleport"
primary_contact: "rjones@goteleport.com"
auto_ccs :
  - "adam@adalogics.com"
  - "teleport-dev@goteleport.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
