homepage: "https://github.com/tikitu/jsmin"
language: python
main_repo: "https://github.com/tikitu/jsmin"
fuzzing_engines:
- libfuzzer
sanitizers:
- address
- undefined
vendor_ccs:
- "david@adalogics.com"
