fuzzing_engines:
- libfuzzer
homepage: https://github.com/pyparsing/pyparsing
language: python
main_repo: https://github.com/pyparsing/pyparsing
sanitizers:
- address
- undefined
vendor_ccs:
- david@adalogics.com
- adam@adalogics.com
- riccardo.schirone@trailofbits.com
- facundo.tuesca@trailofbits.com
