homepage: "https://dateutil.readthedocs.io/en/stable/"
language: python
vendor_ccs:
- "p.antoine@catenacyber.fr"
- "david@adalogics.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
main_repo: "https://github.com/dateutil/dateutil"
