homepage: "https://github.com/AOMediaCodec/libavif"
language: c++
primary_contact: "joedrago@gmail.com"
auto_ccs:
  - "fgalligan@google.com"
  - "jzern@google.com"
  - "wtc@google.com"
  - "yguyon@google.com"
main_repo: 'https://github.com/AOMediaCodec/libavif.git'
