homepage: "http://www.littlecms.com/"
language: c++
primary_contact: "marti.maria.s@gmail.com"
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - undefined
  - memory
architectures:
  - x86_64
  - i386
