homepage: "https://github.com/espeak-ng/espeak-ng"
language: c++
primary_contact: "sascha@brawer.ch"
auto_ccs :
- "p.antoine@catenacyber.fr"

sanitizers:
- address
fuzzing_engines:
- libfuzzer
- afl
main_repo: 'https://github.com/espeak-ng/espeak-ng'
