homepage: "https://github.com/espeak-ng/espeak-ng"
language: c++
primary_contact: "msclrhd@gmail.com"
auto_ccs:
- "valdis.vitolins@odo.lv"
- "p.antoine@catenacyber.fr"
- "sascha@brawer.ch"

sanitizers:
- address
fuzzing_engines:
- libfuzzer
- afl
main_repo: 'https://github.com/espeak-ng/espeak-ng'
