homepage: "https://github.com/FasterXML/woodstox"
language: jvm
primary_contact: "tatu@fasterxml.com"
auto_ccs:
  - "wagner@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "glendowne@code-intelligence.com"
fuzzing_engines:
  - libfuzzer
main_repo: "https://github.com/FasterXML/woodstox"
sanitizers:
  - address
